apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chaos-zookoo.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chaos-zookoo.labels" . | nindent 4 }}
data:
  config.yaml: |
{{- range $i, $scenario := .Values.configs }}
{{- if gt $i 0 }}
    ---
{{- end }}
{{ toYaml $scenario | trim | indent 4 }}
{{- end }}
