{{- range .Values.extraSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "chaos-zookoo.labels" $ | nindent 4 }}
type: Opaque
{{- if .data }}
data:
  {{- range $k, $v := .data }}
  {{ $k }}: {{ $v }}
  {{- end }}
{{- end }}
{{- if .stringData }}
stringData:
  {{- toYaml .stringData | nindent 2 }}
{{- end }}
{{- end }}
