apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chaos-zookoo.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chaos-zookoo.labels" . | nindent 4 }}
type: Opaque
data:
  K8S_HOST: {{ .Values.k8s.host | b64enc }}
  K8S_CLUSTER_CERT: {{ .Values.k8s.clusterCert | b64enc }}
  K8S_TOKEN: {{ .Values.k8s.token | b64enc }}
