apiVersion: v1
kind: Service
metadata:
  name: {{ include "chaos-zookoo.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chaos-zookoo.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "chaos-zookoo.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      name: prometheus
      port: {{ .Values.monitoring.prometheus.port }}
      targetPort: {{ .Values.monitoring.prometheus.port }}
