{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "chaos-zookoo.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chaos-zookoo.labels" . | nindent 4 }}
{{- end }}
